# Generated by Django 4.2.7 on 2025-09-11 12:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('requires_gateway', models.BooleanField(default=True, verbose_name='requires gateway')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='minimum amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum amount')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='fixed fee')),
                ('percentage_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, verbose_name='percentage fee')),
                ('display_name_en', models.CharField(max_length=100, verbose_name='display name (English)')),
                ('display_name_ar', models.CharField(max_length=100, verbose_name='display name (Arabic)')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='icon class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='currency')),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='fees')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='net amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('gateway_name', models.CharField(max_length=50, verbose_name='gateway name')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='gateway transaction ID')),
                ('gateway_reference', models.CharField(blank=True, max_length=255, verbose_name='gateway reference')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('gateway_webhook_data', models.JSONField(blank=True, default=dict, verbose_name='gateway webhook data')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='customer phone')),
                ('customer_name', models.CharField(max_length=255, verbose_name='customer name')),
                ('billing_address', models.JSONField(blank=True, default=dict, verbose_name='billing address')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=100, unique=True, verbose_name='refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refund amount')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='currency')),
                ('reason', models.TextField(verbose_name='refund reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, verbose_name='gateway refund ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'payment_refunds',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100, unique=True, verbose_name='webhook ID')),
                ('gateway_name', models.CharField(max_length=50, verbose_name='gateway name')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('raw_data', models.JSONField(default=dict, verbose_name='raw data')),
                ('headers', models.JSONField(default=dict, verbose_name='headers')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('processing_attempts', models.PositiveIntegerField(default=0, verbose_name='processing attempts')),
                ('last_processing_error', models.TextField(blank=True, verbose_name='last processing error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'db_table': 'payment_webhooks',
                'indexes': [models.Index(fields=['gateway_name', 'event_type'], name='payment_web_gateway_40efe5_idx'), models.Index(fields=['is_processed', 'created_at'], name='payment_web_is_proc_3368ca_idx'), models.Index(fields=['transaction'], name='payment_web_transac_9fe51d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payment_tra_order_i_650087_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'created_at'], name='payment_tra_user_id_ec207b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway_transaction_id'], name='payment_tra_gateway_532615_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payment_tra_status_ea288f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['refund_id'], name='payment_ref_refund__493500_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['transaction', 'status'], name='payment_ref_transac_856cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['status', 'created_at'], name='payment_ref_status_3acb49_idx'),
        ),
    ]
