name: soleva

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: soleva_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - soleva_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    container_name: soleva_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - soleva_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend
  backend:
    build:
      context: ./soleva back end
      dockerfile: Dockerfile
    container_name: soleva_backend
    restart: unless-stopped
    environment:
      # Django Settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      
      # Database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      
      # Redis
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      
      # Email
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      
      # Payment Gateways
      - PAYMOB_API_KEY=${PAYMOB_API_KEY}
      - PAYMOB_SECRET_KEY=${PAYMOB_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      
      # Analytics
      - FACEBOOK_PIXEL_ID=${FACEBOOK_PIXEL_ID}
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - TIKTOK_PIXEL_ID=${TIKTOK_PIXEL_ID}
      - SNAPCHAT_PIXEL_ID=${SNAPCHAT_PIXEL_ID}
      
      # Admin
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - backend_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - soleva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery:
    build:
      context: ./soleva back end
      dockerfile: Dockerfile
    container_name: soleva_celery
    restart: unless-stopped
    command: celery -A soleva_backend worker -l info --concurrency=4
    environment:
      # Same as backend
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    volumes:
      - media_volume:/app/media
      - celery_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - soleva_network
    healthcheck:
      test: ["CMD", "celery", "-A", "soleva_backend", "inspect", "ping"]
      interval: 60s
      timeout: 10s
      retries: 3

  # Celery Beat Scheduler
  celery-beat:
    build:
      context: ./soleva back end
      dockerfile: Dockerfile
    container_name: soleva_celery_beat
    restart: unless-stopped
    command: celery -A soleva_backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      # Same as backend
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    volumes:
      - celery_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - soleva_network

  # React Frontend
  frontend:
    build:
      context: ./soleva front end
      dockerfile: Dockerfile
    container_name: soleva_frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=https://${DOMAIN}/api
      - VITE_APP_NAME=Soleva
      - VITE_NODE_ENV=production
      - VITE_GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - VITE_FACEBOOK_PIXEL_ID=${FACEBOOK_PIXEL_ID}
      - VITE_TIKTOK_PIXEL_ID=${TIKTOK_PIXEL_ID}
      - VITE_SNAPCHAT_PIXEL_ID=${SNAPCHAT_PIXEL_ID}
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - soleva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy & SSL
  nginx:
    image: nginx:alpine
    container_name: soleva_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/var/www/static:ro
      - media_volume:/var/www/media:ro
      - frontend_build:/var/www/html:ro
      - nginx_logs:/var/log/nginx
      - certbot_webroot:/var/www/certbot:ro
      - letsencrypt_certs:/etc/letsencrypt:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - soleva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: soleva_certbot
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d ${DOMAIN} -d www.${DOMAIN}
    depends_on:
      - nginx
    networks:
      - soleva_network
    restart: "no"

  # SSL Certificate Renewal (runs periodically)
  certbot-renew:
    image: certbot/certbot
    container_name: soleva_certbot_renew
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt
    command: renew --quiet --no-self-upgrade
    depends_on:
      - nginx
    networks:
      - soleva_network
    restart: "no"
    profiles:
      - renewal

# Named Volumes for Data Persistence
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  frontend_build:
    driver: local
  backend_logs:
    driver: local
  celery_logs:
    driver: local
  nginx_logs:
    driver: local
  letsencrypt_certs:
    driver: local
  certbot_webroot:
    driver: local
  certbot_logs:
    driver: local

# Networks
networks:
  soleva_network:
    driver: bridge
