# Generated by Django 4.2.7 on 2025-09-11 00:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash_sales/banners/', verbose_name='banner image')),
                ('banner_color', models.CharField(default='#ff4444', max_length=7, verbose_name='banner color')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='text color')),
                ('display_priority', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first', verbose_name='display priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='show countdown timer')),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, null=True, verbose_name='max uses per customer')),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='total usage limit')),
                ('current_usage_count', models.PositiveIntegerField(default=0, verbose_name='current usage count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'db_table': 'offers_flash_sales',
                'ordering': ['-display_priority', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('offer_type', models.CharField(choices=[('buy_x_get_y_free', 'Buy X Get Y Free'), ('buy_x_get_discount', 'Buy X Get Discount'), ('buy_x_free_shipping', 'Buy X Get Free Shipping'), ('bundle_discount', 'Bundle Discount')], max_length=20, verbose_name='offer type')),
                ('buy_quantity', models.PositiveIntegerField(default=2, help_text='Minimum quantity to buy', verbose_name='buy quantity')),
                ('free_quantity', models.PositiveIntegerField(default=1, help_text='Number of free items', verbose_name='free quantity')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='discount value')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, null=True, verbose_name='max uses per customer')),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='total usage limit')),
                ('current_usage_count', models.PositiveIntegerField(default=0, verbose_name='current usage count')),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum order amount')),
                ('button_text_en', models.CharField(default='Activate Offer', max_length=100, verbose_name='button text (English)')),
                ('button_text_ar', models.CharField(default='تفعيل العرض', max_length=100, verbose_name='button text (Arabic)')),
                ('button_color', models.CharField(default='#ff4444', max_length=7, verbose_name='button color')),
                ('highlight_color', models.CharField(default='#ffeb3b', max_length=7, verbose_name='highlight color')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('show_on_product_page', models.BooleanField(default=True, verbose_name='show on product page')),
                ('show_timer', models.BooleanField(default=True, verbose_name='show countdown timer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='special_offers', to='products.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='special_offers', to='products.product')),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'db_table': 'offers_special_offers',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='OfferUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='order ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='discount amount')),
                ('free_shipping_applied', models.BooleanField(default=False, verbose_name='free shipping applied')),
                ('free_items_json', models.JSONField(blank=True, default=list, verbose_name='free items')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='order total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('flash_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='offers.flashsale')),
                ('special_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='offers.specialoffer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Usage',
                'verbose_name_plural': 'Offer Usages',
                'db_table': 'offers_usage',
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount value')),
                ('quantity_limit', models.PositiveIntegerField(blank=True, help_text='Max quantity available at this price', null=True, verbose_name='quantity limit')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='sold quantity')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='offers.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Flash Sale Product',
                'verbose_name_plural': 'Flash Sale Products',
                'db_table': 'offers_flash_sale_products',
                'ordering': ['-is_featured', 'display_order', 'product__name_en'],
            },
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='offers_flas_is_acti_4e0725_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['display_priority'], name='offers_flas_display_264052_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='offers_spec_is_acti_bc4148_idx'),
        ),
        migrations.AddIndex(
            model_name='specialoffer',
            index=models.Index(fields=['offer_type'], name='offers_spec_offer_t_611dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['user', 'created_at'], name='offers_usag_user_id_9882c5_idx'),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['order_id'], name='offers_usag_order_i_fbb3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['flash_sale'], name='offers_usag_flash_s_c94fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['special_offer'], name='offers_usag_special_e8e375_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerusage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('flash_sale__isnull', False), ('special_offer__isnull', True)), models.Q(('flash_sale__isnull', True), ('special_offer__isnull', False)), _connector='OR'), name='offer_usage_exclusive_offer_type'),
        ),
        migrations.AddIndex(
            model_name='flashsaleproduct',
            index=models.Index(fields=['flash_sale', 'is_featured'], name='offers_flas_flash_s_a8e98c_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsaleproduct',
            index=models.Index(fields=['display_order'], name='offers_flas_display_6fc612_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleproduct',
            unique_together={('flash_sale', 'product')},
        ),
    ]
