# Generated by Django 4.2.7 on 2025-09-11 00:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Banner Title')),
                ('message_en', models.TextField(verbose_name='Message (English)')),
                ('message_ar', models.TextField(verbose_name='Message (Arabic)')),
                ('banner_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('announcement', 'Announcement')], default='info', max_length=20, verbose_name='Banner Type')),
                ('display_location', models.CharField(choices=[('top', 'Top of Page'), ('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('all_pages', 'All Pages'), ('homepage', 'Homepage Only'), ('product_pages', 'Product Pages Only'), ('checkout', 'Checkout Only')], default='top', max_length=20, verbose_name='Display Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Is Dismissible')),
                ('auto_hide_after', models.PositiveIntegerField(blank=True, null=True, verbose_name='Auto Hide After (seconds)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('background_color', models.CharField(blank=True, max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(blank=True, max_length=7, verbose_name='Text Color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class')),
                ('cta_text_en', models.CharField(blank=True, max_length=50, verbose_name='CTA Text (English)')),
                ('cta_text_ar', models.CharField(blank=True, max_length=50, verbose_name='CTA Text (Arabic)')),
                ('cta_url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher numbers show first', verbose_name='Priority')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification Banner',
                'verbose_name_plural': 'Notification Banners',
                'ordering': ['-priority', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(default='Soleva', max_length=100, verbose_name='Site Name (English)')),
                ('site_name_ar', models.CharField(default='سوليفا', max_length=100, verbose_name='Site Name (Arabic)')),
                ('site_description_en', models.TextField(blank=True, verbose_name='Site Description (English)')),
                ('site_description_ar', models.TextField(blank=True, verbose_name='Site Description (Arabic)')),
                ('primary_email', models.EmailField(default='info@solevaeg.com', max_length=254, verbose_name='Primary Email')),
                ('support_email', models.EmailField(default='support@solevaeg.com', max_length=254, verbose_name='Support Email')),
                ('sales_email', models.EmailField(default='sales@solevaeg.com', max_length=254, verbose_name='Sales Email')),
                ('business_email', models.EmailField(default='business@solevaeg.com', max_length=254, verbose_name='Business Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Number')),
                ('address_en', models.TextField(blank=True, verbose_name='Address (English)')),
                ('address_ar', models.TextField(blank=True, verbose_name='Address (Arabic)')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/share/1BNS1QbzkP/', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('meta_keywords_en', models.TextField(blank=True, verbose_name='Meta Keywords (English)')),
                ('meta_keywords_ar', models.TextField(blank=True, verbose_name='Meta Keywords (Arabic)')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('business_hours', models.TextField(blank=True, verbose_name='Business Hours')),
                ('shipping_info_en', models.TextField(blank=True, verbose_name='Shipping Information (English)')),
                ('shipping_info_ar', models.TextField(blank=True, verbose_name='Shipping Information (Arabic)')),
                ('return_policy_en', models.TextField(blank=True, verbose_name='Return Policy (English)')),
                ('return_policy_ar', models.TextField(blank=True, verbose_name='Return Policy (Arabic)')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('maintenance_message_en', models.TextField(blank=True, verbose_name='Maintenance Message (English)')),
                ('maintenance_message_ar', models.TextField(blank=True, verbose_name='Maintenance Message (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('section_type', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('flash_sale_banner', 'Flash Sale Banner'), ('featured_products', 'Featured Products'), ('brand_story', 'Brand Story'), ('testimonials', 'Testimonials'), ('newsletter', 'Newsletter Section'), ('social_media', 'Social Media Section'), ('announcement_bar', 'Announcement Bar'), ('about_us', 'About Us Section'), ('contact_info', 'Contact Information'), ('footer_content', 'Footer Content'), ('custom', 'Custom Section')], max_length=50, verbose_name='Section Type')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Title (Arabic)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Subtitle (English)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='Subtitle (Arabic)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('content_ar', models.TextField(blank=True, verbose_name='Content (Arabic)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website_sections/', verbose_name='Image')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='website_sections/backgrounds/', verbose_name='Background Image')),
                ('video_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Video URL')),
                ('cta_text_en', models.CharField(blank=True, max_length=50, verbose_name='CTA Text (English)')),
                ('cta_text_ar', models.CharField(blank=True, max_length=50, verbose_name='CTA Text (Arabic)')),
                ('cta_url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('background_color', models.CharField(blank=True, help_text='Hex color code (e.g., #ffffff)', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(blank=True, help_text='Hex color code (e.g., #000000)', max_length=7, verbose_name='Text Color')),
                ('custom_css', models.TextField(blank=True, verbose_name='Custom CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Website Section',
                'verbose_name_plural': 'Website Sections',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_en', models.CharField(max_length=200, verbose_name='Subject (English)')),
                ('subject_ar', models.CharField(max_length=200, verbose_name='Subject (Arabic)')),
                ('message_en', models.TextField(verbose_name='Message (English)')),
                ('message_ar', models.TextField(verbose_name='Message (Arabic)')),
                ('message_type', models.CharField(choices=[('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('order_update', 'Order Update'), ('support_reply', 'Support Reply'), ('welcome', 'Welcome Message'), ('newsletter', 'Newsletter'), ('announcement', 'Announcement'), ('system', 'System Message')], default='system', max_length=20, verbose_name='Message Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is Important')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='user_messages/', verbose_name='Attachment')),
                ('action_url', models.URLField(blank=True, help_text='URL for call-to-action button', verbose_name='Action URL')),
                ('action_text_en', models.CharField(blank=True, max_length=50, verbose_name='Action Text (English)')),
                ('action_text_ar', models.CharField(blank=True, max_length=50, verbose_name='Action Text (Arabic)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Messages',
                'ordering': ['-is_important', '-sent_at'],
            },
        ),
    ]
