# Generated by Django 4.2.7 on 2025-09-11 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='session key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'shopping_carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='product ID')),
                ('variant_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='variant ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('product_image', models.URLField(blank=True, verbose_name='product image')),
                ('variant_attributes', models.JSONField(blank=True, default=dict, verbose_name='variant attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='SavedForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='product ID')),
                ('variant_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='variant ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('product_image', models.URLField(blank=True, verbose_name='product image')),
                ('variant_attributes', models.JSONField(blank=True, default=dict, verbose_name='variant attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved for Later',
                'verbose_name_plural': 'Saved for Later',
                'db_table': 'saved_for_later',
                'indexes': [models.Index(fields=['user'], name='saved_for_l_user_id_edaaf2_idx'), models.Index(fields=['product_id'], name='saved_for_l_product_ba52b0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedforlater',
            constraint=models.UniqueConstraint(fields=('user', 'product_id', 'variant_id'), name='unique_saved_product_variant'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_items_cart_id_3caa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product_id'], name='cart_items_product_6a1de7_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_id', 'variant_id'), name='unique_cart_product_variant'),
        ),
    ]
