# Generated by Django 4.2.7 on 2025-09-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('code_length', models.IntegerField(default=6)),
                ('expiry_minutes', models.IntegerField(default=5)),
                ('max_attempts', models.IntegerField(default=5)),
                ('resend_cooldown_minutes', models.IntegerField(default=2)),
                ('rate_limit_requests', models.IntegerField(default=3)),
                ('rate_limit_window_minutes', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OTP Configuration',
                'verbose_name_plural': 'OTP Configurations',
            },
        ),
        migrations.CreateModel(
            name='SecurityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('password_reset_alert', 'Password Reset Alert'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked'), ('login_from_new_device', 'Login from New Device')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Notification',
                'verbose_name_plural': 'Security Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('login_verification', 'Login Verification'), ('email_verification', 'Email Verification')], max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('attempts_count', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_invalidated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otp.otpconfiguration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Request',
                'verbose_name_plural': 'OTP Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_code', models.CharField(max_length=10)),
                ('is_successful', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('otp_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otp.otprequest')),
            ],
            options={
                'verbose_name': 'OTP Attempt Log',
                'verbose_name_plural': 'OTP Attempt Logs',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['email', 'otp_type'], name='otp_otprequ_email_2cff23_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['code'], name='otp_otprequ_code_773483_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['expires_at'], name='otp_otprequ_expires_1ff11d_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['created_at'], name='otp_otprequ_created_6bd9e8_idx'),
        ),
    ]
