# Generated by Django 4.2.7 on 2025-09-11 12:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('additional_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='additional shipping cost')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, verbose_name='estimated delivery days')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'shipping_cities',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='name (Arabic)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('base_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8, verbose_name='base shipping cost')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'Governorate',
                'verbose_name_plural': 'Governorates',
                'db_table': 'shipping_governorates',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='base cost')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='cost per kg')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='free shipping threshold')),
                ('min_delivery_days', models.PositiveIntegerField(default=1, verbose_name='minimum delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(default=7, verbose_name='maximum delivery days')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='maximum weight (kg)')),
                ('max_dimensions', models.CharField(blank=True, max_length=50, verbose_name='maximum dimensions (LxWxH cm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'db_table': 'shipping_methods',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('governorates', models.ManyToManyField(related_name='shipping_zones', to='shipping.governorate')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'db_table': 'shipping_zones',
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='base cost')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='cost per kg')),
                ('min_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, verbose_name='minimum weight (kg)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='maximum weight (kg)')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minimum order value')),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum order value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'db_table': 'shipping_rates',
            },
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['code'], name='shipping_me_code_960ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active', 'display_order'], name='shipping_me_is_acti_93ff6c_idx'),
        ),
        migrations.AddIndex(
            model_name='governorate',
            index=models.Index(fields=['code'], name='shipping_go_code_c0b324_idx'),
        ),
        migrations.AddIndex(
            model_name='governorate',
            index=models.Index(fields=['is_active', 'display_order'], name='shipping_go_is_acti_c09c24_idx'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shipping.governorate'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['zone', 'method'], name='shipping_ra_zone_id_321fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['is_active'], name='shipping_ra_is_acti_bc159d_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingrate',
            constraint=models.UniqueConstraint(fields=('zone', 'method', 'min_weight', 'min_order_value'), name='unique_shipping_rate'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['governorate', 'is_active'], name='shipping_ci_governo_3d5534_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name_en'], name='shipping_ci_name_en_177c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name_ar'], name='shipping_ci_name_ar_055495_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('governorate', 'name_en'), name='unique_city_per_governorate'),
        ),
    ]
